name: CPH Ticket Monitor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    # Force run even on schedule
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies
      run: |
        pip install selenium
        pip install webdriver-manager
        pip install requests
        pip install beautifulsoup4
    
    - name: Run ticket monitor
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python ticket_monitor.py
    
    # Optional: Run multiple times within the 5-minute window
    - name: Wait 1 minute
      run: sleep 60
    
    - name: Run ticket monitor (2nd check)
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python ticket_monitor.py
    
    - name: Wait 1 minute
      run: sleep 60
    
    - name: Run ticket monitor (3rd check)
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python ticket_monitor.py
    
    - name: Wait 1 minute
      run: sleep 60
    
    - name: Run ticket monitor (4th check)
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python ticket_monitor.py
